<h1>Privacy Policy</h1>
<p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Under data protection laws, we are required to provide you with certain information about who we are, how we process your personal data and for what purposes, and your rights in relation to your personal data.&nbsp;</span></p>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4;mso-list:l4 level1 lfo1;tab-stops: list 36.0pt"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Introduction</span></u></b><b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"></span></b></li>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">1.1&nbsp; We are committed to safeguarding the privacy of our website visitors and service users and to protecting your<br>personal data ands respecting privacy.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">1.2 This policy applies where we are acting as a data controller with respect to the personal data of our website visitors and<br>service users; in other words, where we determine the purposes and means of the processing of that personal data.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">1.3 We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of our website and<br>services, we will ask you to consent to our use of cookies when you first visit our website.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">1.4 Our website incorporates privacy controls which affect how we will process your personal data. By using the privacy controls, you can specify whether you would like to receive direct marketing communications and limit the publication of your information.&nbsp;</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">1.5 In this policy, &#8220;we&#8221;, &#8220;us&#8221;<br>and &#8220;our&#8221; refer to Beach Road Dental Management&nbsp;</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;text-align:center;line-height:normal;mso-outline-level:3" align="center"><b><u><span style="font-size:13.5pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB">Contact details</span></u></b><b><span style="font-size:13.5pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></b></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;text-align:center;line-height:normal" align="center"><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Beach Dental Management</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;text-align:center;line-height:normal" align="center"><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Littlehampton</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;text-align:center;line-height:normal" align="center"><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">BN17 5HT</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;text-align:center;line-height:normal" align="center"><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Or email at:<br>contact@beachdentalpractice.com </span></p>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4;mso-list:l14 level1 lfo2; tab-stops:list 36.0pt"><b><u><span style="font-size:12.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">How do<br>     we use your personal data</span></u></b><b><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></b></li>
</ol>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-list:l11 level1 lfo3;tab-stops:list 36.0pt"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB">&nbsp;</span></li>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:4;mso-list:l11 level2 lfo3; tab-stops:list 72.0pt"><b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">2.1.The data we collect about you:</span></b></li>
</ol>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">We may collect, use, store and transfer different kinds of personal data about you as follows: Identity data, Contact data,<br>Financial data, Transaction data, Device data, Content data, Profile data, Usage data, Marketing and Communications data, Location data.</span></p>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-list:l6 level1 lfo4;tab-stops:list 36.0pt"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB">&nbsp;</span></li>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l6 level2 lfo4; tab-stops:list 72.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">2.2.We do not collect any Special Categories or personal data about you (this includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health, and genetic and biometric data). Nor do we collect any information about criminal convictions and offences.</span></b></li>
</ol>
</ol>
<p><br></p>
<ol type="1" start="1">
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l9 level2 lfo5; tab-stops:list 72.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">2.3.We will collect and process the following data about you:</span></b></li>
</ol>
</ol>
<ol type="1" start="1">
<ol type="1" start="1">
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l8 level3 lfo6; tab-stops:list 108.0pt"><b><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Information you give us. This is information (including Identity, Contact, Financial, and Marketing and Communications Data) you consent to giving<br>       us about you by filling in forms on the Website or by corresponding with us (for example, by email or chat). It includes information you provide<br>       when you register to our website, subscribe to any of our Services, search for a Service, share data via website social media functions,<br>       enter a competition, promotion or survey, or another activities commonly carried out in connection with using of website and when you report a<br>       problem with a website, our Services, or any of Our Sites. If you contact us, we will keep a record of that correspondence.&nbsp;</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l8 level3 lfo6; tab-stops:list 108.0pt"><b><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Information we collect about you and your device. Each time you Our Sites we will automatically collect personal data including Device, Content and Usage Data. We collect this data using cookies and other similar technologies.<br>       Please see our cookie policy for further details.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l8 level3 lfo6; tab-stops:list 108.0pt"><b><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Information we receive from other sources including third parties and publicly available sources. We will receive personal data about you from various third parties [and public sources] as set out below&nbsp;</span></b></li>
</ol>
</ol>
</ol>
<ul type="disc">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l1 level1 lfo7;tab-stops: list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Device Data from the following parties:</span></b></li>
</ul>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5"><b><span style="font-size:10.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">analytics providers [such as Google based outside the EU];</span></b></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5"><b><span style="font-size:10.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">advertising networks based inside OR outside the EU]; and</span></b></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5"><b><span style="font-size:10.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">search information providers based inside OR outside the EU.</span></b></p>
<ul type="disc">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l16 level1 lfo8; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Contact, Financial and Transaction Data from providers of technical, payment and delivery services based inside OR outside the EU;</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l16 level1 lfo8; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Identity and Contact Data from data brokers or aggregators based inside OR outside the EU;</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l16 level1 lfo8; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Identity and Contact Data from publicly available sources [such as Companies House and the electoral register based inside the EU]</span></b></li>
</ul>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5"><b><span style="font-size:10.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">&nbsp;</span></b></p>
<ol type="1" start="3">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4;mso-list:l13 level1 lfo9; tab-stops:list 36.0pt"><b><u><span style="font-size:12.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Cookies</span></u></b><b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"></span></b></li>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">3.1 A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser<br>and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">3.2 Cookies may be either &#8220;persistent&#8221; cookies or &#8220;session&#8221; cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">3.3 Cookies do not typically contain any information that personally identifies a user, but personal data that we store<br>about you may be linked to the information stored in and obtained from cookies.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">4.3. Cookies that we use</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">4.3.1. We use cookies for the following purposes:</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">(a) authentication and status &#8211; we use cookies to identify you when you visit our website and as you navigate our website, and to determine if you are logged into the website</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">&nbsp;(b) personalisation &#8211; we use cookies to store information about your preferences and to personalise the website for you</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">&nbsp;(c) security &#8211; we use cookies [as an element of the security measures used to protect user accounts, including preventing<br>fraudulent use of login credentials, and to protect our website and services<br>generally)</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">&nbsp;(d) advertising &#8211; we use cookies [to help us to display advertisements that will be relevant to you)</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">&nbsp;(e) analysis &#8211; we use cookies [to help us to analyse the use and performance of our website and services)</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">&nbsp;(f) cookie consent &#8211; we use cookies to store your preferences in relation to the use of cookies more generally&nbsp;</span></p>
<ol type="1" start="5">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4;mso-list:l12 level1 lfo10; tab-stops:list 36.0pt"><b><u><span style="font-size:12.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Providing<br>     your personal data to others</span></u></b><b><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></b></li>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">5.1 We may disclose your personal data to our insurers and/or professional advisers insofar as reasonably necessary for the<br>purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice, or the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.&nbsp; We may also disclose your information to charities associated with the competition and any entity for whom we are working in facilitating or organising the competition</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">5.2 Your personal data held in our website database will be stored on the servers of our hosting services providers.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">5.3 We may disclose specify personal data category or categories to our suppliers or subcontractors insofar as reasonably<br>necessary&nbsp;</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">5.4 In addition to the specific disclosures of personal data set out in Section 4, we may disclose your personal data where<br>such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such<br>disclosure is necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.</span></p>
<ol type="1" start="6">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4;mso-list:l2 level1 lfo11; tab-stops:list 36.0pt"><b><u><span style="font-size:12.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">International<br>     transfers of your personal data</span></u></b><b><span style="font-size: 12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></b></li>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">6.1 In this Section, we provide information about the circumstances in which your personal data may be transferred to countries<br>outside the European Economic Area (EEA).</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">6.2 The hosting facilities for our website are situated in UK. The European Commission has made an &#8220;adequacy decision&#8221; with respect to the data protection laws of each of these countries. Transfers to each of these countries] will be protected by appropriate safeguards, namely the use of standard data protection clauses adopted or approved by the European Commission.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">6.3 You acknowledge that personal data that you submit for publication through our website or services may be available, via<br>the internet, around the world. We cannot prevent the use (or misuse) of such personal data by others.</span></p>
<ol type="1" start="7">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4;mso-list:l3 level1 lfo12; tab-stops:list 36.0pt"><b><u><span style="font-size:12.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Retaining<br>     and deleting personal data</span></u></b><b><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></b></li>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">7.1 This Section sets out our data retention policies and procedure, which are designed to help ensure that we comply with<br>our legal obligations in relation to the retention and deletion of personal <br>data.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">7.2 Personal data that we process for any purpose<br>or purposes shall not be kept for longer than is necessary for that purpose or those purposes.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">7.3 Notwithstanding the other provisions of this<br>Section 6, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</span></p>
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-list:l15 level1 lfo13;tab-stops:list 36.0pt"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB">All information you provide to us is stored on our secure servers.<br>     Any payment transactions [carried out by us or our chosen third-party provider of payment processing services] will be encrypted using Secured Sockets Layer technology OR alternative encryption technology. Where we have given you or where you have chosen a password that enables you to access certain parts of Our Sites, you are responsible for keeping this<br>     password confidential. We ask you not to share a password with anyone.</span></li>
</ol>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Once we have received your information, we will use strict procedures and security features to try to prevent your personal data<br>from being accidentally lost, used or accessed in an unauthorised way.&nbsp;</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">We have put in place procedures to deal with any suspected personal data breach and will notify you and any applicable regulator<br>when we are legally required to do so.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Data retention</span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">By law we have to keep basic information about our customers (including Contact, Identity, Financial and Transaction Data) for six<br>years after they cease being customers for tax purposes.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">In some circumstances you can ask us to delete your data: see [Your legal rights] below for further information.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">In some circumstances we will anonymise your personal data (so that it can no longer be associated with you) for research or<br>statistical purposes, in which case we may use this information indefinitely without further notice to you.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">In the event that you do not use our website for a period of twelve calendar months then we will treat the account as expired and<br>your personal data may be deleted.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Your legal rights</span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">You have rights under data protection laws in relation to your personal data. We can provide further information on this or<br>you may wish to take your own legal advice.You have the right to ask us not to continue to process your personal data for marketing purposes.&nbsp; You can exercise any of these rights at any time by contacting us at our address indicated above.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">If you should have a complaint concerning the data that we hold, you are able to contact the Information Commissioner aw <a href="http://www.ico.gov.uk"><span style="color:blue">www.ico.gov.uk</span></a>.&nbsp;<br>We recommend that you try to resolve any issues with us first.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Glossary</span></u></b><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Lawful basis</span></u></b><span style="font-size: 12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Consent</span></u></b><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"> means<br>processing your personal data where you have signified your agreement by a statement or clear opt-in to processing for a specific purpose. Consent will only be valid if it is a freely given, specific, informed and unambiguous indication of what you want. You can withdraw your consent at any time by contacting us.&nbsp;</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Legitimate Interest</span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"> means the interest of our business in conducting and managing our business to enable us to give you the best service/product and the best and most secure experience. We make sure we consider and balance any potential impact on you (both positive and negative) and your rights before we process your personal data for our legitimate interests. We do not use your personal data for activities where our interests are overridden by the impact on you (unless we have your consent or are otherwise required or permitted to by law).<br>You can obtain further information about how we assess our legitimate interests against any potential impact on you in respect of specific activities by contacting us.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Performance of Contract</span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"> means processing your data where it is necessary for the performance of a contract to which you are a party or to take steps at your request before entering into such a contract.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Comply with a legal obligation </span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB">means processing your personal data where it is necessary for compliance with a legal obligation that we are subject to.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Third parties</span></u></b><span style="font-size: 12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Internal third parties</span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Other companies acting as joint controllers or processors who&nbsp; provide IT and system administration services or&nbsp; undertake leadership reporting].</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><b><u><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">External third parties</span></u></b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB"></span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Service providers who provide IT and system administration services. Professional advisers acting as processors or joint<br>controllers including lawyers, bankers, auditors and insurers who provide consultancy, banking, legal, insurance and accounting services. HM Revenue and Customs, regulators and other authorities [acting as processors or joint controllers] based in the UK who require reporting of processing activities in certain circumstances.</span></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4"><b><u><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Your legal rights</span></u></b><b><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB"></span></b></p>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">You have the right to:</span></p>
<ul type="disc">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l7 level1 lfo14; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Request access to your personal data (commonly known as a &#8220;data subject access request&#8221;). This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully processing it.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l7 level1 lfo14; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Request correction of the personal data that we hold about you. This enables you to have any incomplete or inaccurate data we hold about you corrected, though we may need to verify the accuracy of the new data you provide to us.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l7 level1 lfo14; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Request erasure of your personal data. This enables you to ask us to delete or remove personal data where there is no good reason for us continuing to process it. You also have the right to ask us to delete or remove your personal data where you have successfully exercised your right to object to processing (see below), where we may have processed your information unlawfully or where we are required to erase your personal data to comply with local law. Note, however, that we may not always be able to comply with your request of erasure for specific legal reasons which will be notified to you, if applicable, at the time of your request.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l7 level1 lfo14; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Object to processing of your personal data where we are relying on a legitimate interest (or those of a third party)<br>     and there is something about your particular situation which makes you want to object to processing on this ground as you feel it impacts on your&nbsp; fundamental rights and freedoms. You also have the right to object where we are processing your personal data for direct marketing purposes. In some cases, we may demonstrate that we have compelling legitimate grounds to process your information which override your rights and freedoms. Request restriction of processing of your personal data. This enables you to ask us to suspend the processing of your personal data in the following scenarios:</span></b></li>
</ul>
<ol type="1" start="1">
<ol type="1" start="1">
<ol type="1" start="1">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l5 level3 lfo15; tab-stops:list 108.0pt"><b><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">if<br>       you want us to establish the data&#8217;s accuracy; where our use of the data is unlawful but you do not want us to erase it; where you need us to hold the data even if we no longer require it as you need it to establish, exercise or defend legal claims; or</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt: auto;line-height:normal;mso-outline-level:5;mso-list:l5 level3 lfo15; tab-stops:list 108.0pt"><b><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">you have objected to our use of your data but we need to verify whether we have overriding legitimate grounds to use it.</span></b></li>
</ol>
</ol>
</ol>
<ul type="disc">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l10 level1 lfo16; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Request the transfer of your personal data to you or to a third party. We will provide to you, or a third party you have<br>     chosen, your personal data in a structured, commonly used, machine-readable format. Note that this right only applies to automated<br>     information which you initially provided consent for us to use or where we used the information to perform a contract with you.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l10 level1 lfo16; tab-stops:list 36.0pt"><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">Withdraw consent at any time where we are relying on consent to process your personal data. However, this will not affect the lawfulness of any processing carried out before you withdraw your consent. If you withdraw your consent, we may not be able to provide certain products or services to you. We will advise you if this is the case at the time you withdraw your consent.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-list:l10 level1 lfo16;tab-stops:list 36.0pt"><span style="font-size:12.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family: &quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language: EN-GB">&nbsp;</span></li>
</ul>
<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:4"><b><u><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Description of categories of personal data</span></u></b><b><span style="font-size:12.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"></span></b></p>
<ul type="disc">
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Identity Data:</span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB"> first name, last name, maiden name, username or similar identifier, marital status, title, date of birth, gender.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Contact Data: </span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">billing address, delivery address, email address and telephone numbers.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Financial Data:</span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB"> bank account and payment card details.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Transaction Data: </span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">includes details about payments to and from you&nbsp;</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Device Data: </span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">includes the type of mobile device you use, a unique device identifier (for example, your Device&#8217;s IMEI number, the MAC address of the Device&#8217;s wireless network interface, or the mobile phone number used by the Device), mobile network information, your mobile operating<br>     system, the type of mobile browser you use, time zone setting.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Content Data: </span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">includes information stored on your Device, including friends&#8217; lists, login information, photos, videos or other digital content,check-ins,</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Profile Data:</span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB"> includes your username and password, in-App purchase history, your interests, preferences, feedback and survey responses.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Usage Data: </span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB">includes details of your use of any of our Apps or your visits to any of Our Sites including, but not limited to, traffic data and other communication data, whether this is required for our own billing purposes or otherwise and the resources that you access.</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Marketing and Communications Data:</span></u></b><b><span style="font-size:10.0pt; font-family:&quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB"><br>     includes your preferences in receiving marketing from us and our third<br>     parties and your communication preferences.&nbsp;</span></b></li>
<li class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto; line-height:normal;mso-outline-level:5;mso-list:l0 level1 lfo17; tab-stops:list 36.0pt"><b><u><span style="font-size:10.0pt;font-family: &quot;Candara&quot;,&quot;sans-serif&quot;;mso-fareast-font-family:&quot;Times New Roman&quot;; mso-bidi-font-family:&quot;Times New Roman&quot;;mso-fareast-language:EN-GB">Location Data:</span></u></b><b><span style="font-size:10.0pt;font-family:&quot;Candara&quot;,&quot;sans-serif&quot;; mso-fareast-font-family:&quot;Times New Roman&quot;;mso-bidi-font-family:&quot;Times New Roman&quot;; mso-fareast-language:EN-GB"> includes your current location disclosed by GPS or other technology</span></b></li>
</ul>
<p class="MsoNormal"><span style="font-family:&quot;Candara&quot;,&quot;sans-serif&quot;">&nbsp;</span></p>
</p>